# Generated by Django 5.2.3 on 2026-04-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactmessage",
            old_name="mobile_no",
            new_name="phone",
        ),
        migrations.RemoveField(
            model_name="contactmessage",
            name="address",
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="grievance_type",
            field=models.CharField(
                choices=[
                    ("Infrastructure Issues", "Infrastructure Issues"),
                    ("Healthcare Services", "Healthcare Services"),
                    ("Education and Schools", "Education and Schools"),
                    ("Water Supply", "Water Supply"),
                    ("Electricity", "Electricity"),
                    ("Sanitation", "Sanitation"),
                    ("Public Transport", "Public Transport"),
                    ("Law and Order", "Law and Order"),
                    ("Land and Property", "Land and Property"),
                    ("Social Welfare Schemes", "Social Welfare Schemes"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(default="General Inquiry", max_length=200),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="message",
            field=models.TextField(default="Other"),
        ),
    ]
