# Generated by Django 5.2.3 on 2026-04-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_volunteer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="interests",
            field=models.CharField(
                choices=[
                    ("Education", "Education Initiatives"),
                    ("Infrastructure", "Infrastructure Development"),
                    ("Women", "Women Empowerment"),
                    ("Agriculture", "Agricultural Support"),
                    ("Healthcare", "Healthcare Programs"),
                    ("Environment", "Environmental Conservation"),
                    ("Youth", "Youth Development"),
                    ("Social", "Social Welfare"),
                ],
                max_length=50,
            ),
        ),
    ]
