# Generated by Django 5.2.3 on 2026-04-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_volunteer_interests"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteer",
            name="is_contacted",
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="interests",
            field=models.CharField(max_length=255),
        ),
    ]
